- name: create an auto-scaling group
  ec2_asg:
    region: "{{ aws_region }}"
    name: "{{ aws_group_name }}"
    state: present
    desired_capacity: 2
    min_size: 2
    max_size: 2
    launch_config_name: "{{ launch_configuration_name }}"
    load_balancers: [ "{{ load_balancer_name }}" ]
    vpc_zone_identifier: "{{ vpc_result.subnets | subnetworks(vpc.web_subnets) | map(attribute='id') | list }}"