---
- name: create a VPC
  ec2_vpc:
    region: "{{ region }}"
    cidr_block: "{{ vpc.cidr }}"
    resource_tags: { "Environment": "{{ env }}", "Name": "demo" }
    internet_gateway: yes
    subnets: "{{ vpc.subnets }}"
    route_tables:
      - subnets: "{{ vpc.web_subnets }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
      - subnets: "{{ vpc.db_subnets }}"
        routes: []
    wait: yes
  register: vpc_result

- name: create web security group
  ec2_group:
    region: "{{ region }}"
    name: "web security group"
    description: "security group of web service instances"
    vpc_id: "{{ vpc_result.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: "{{ vpc.cidr }}"
      - proto: tcp
        from_port: 8081
        to_port: 8081
        cidr_ip: "{{ vpc.cidr }}"
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{ vpc.cidr }}"
  register: web_sg_result