---
- name: ensure Java 7 is not installed
  yum: name=java-1.7.0 state=absent

- name: ensure Java 8 is installed
  yum: name=java-1.8.0 state=present

- name: install yum-s3-iam plugin
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 's3iam.py', dest: '/usr/lib/yum-plugins/' }
    - { src: 's3iam.conf', dest: '/etc/yum/pluginconf.d/' }

- name: add awsdemo repo to yum
  copy: src=awsdemo.repo dest=/etc/yum.repos.d/awsdemo.repo

- name: ensure all packages are up-to-date
  yum: name=* disablerepo="awsdemo" state=latest

- name: create group awsdemo
  group: name=awsdemo

- name: create user awsdemo
  user: name=awsdemo group=awsdemo shell=/bin/bash

- name: create directories
  file: dest={{ item }} state=directory owner=awsdemo group=awsdemo
  with_items:
    - "{{ root_dir }}"
    - "{{ root_dir }}/scripts"
    - "{{ root_log_dir }}"

- name: install useful utilities
  yum: name={{ item }}
  with_items:
    - tree
    - telnet
    - vim-enhanced