server:
  type: default
  requestLog:
    appenders:
      - type: file
        currentLogFilename: {{ root_log_dir }}/requests.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: {{ root_log_dir }}/requests-%d.log
        archivedFileCount: 5
        timeZone: UTC

logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: {{ root_log_dir }}/service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: {{ root_log_dir }}/service-%d.log
      archivedFileCount: 5
      timeZone: UTC

metrics:
  reporters:
    - type: cloudwatch
      namespace: aws-demo
      useRegexFilters: true
      includes:
        - com.aws.demo.service.resource.*